Q_and_A = [
    {'question': 'Wole robić rzeczy w grupie, niż samemu',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Nie zgadzam się'},
    {'question': 'Wole wykonywać czynności stale w ten sam sposób',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Zgadzam sie'},
    {'question': 'Jeżeli próbuje sobie coś wyobrazić, nie sprawia mi problemu utworzenie sobie obrazu w myślach',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Zgadzam sie'},
    {'question': 'Często bywam tak zaabsorbowany jednym tematem, że nie zauważam niczego więcej',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Zgadzam sie'},
    {'question': 'Często słyszę ciche odgłosy, niesłyszalne przez innych',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Zgadzam sie'},
    {'question': 'Często zapamiętuje strzępki informacji, np. numery rejestracyjne samochodów',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Zgadzam sie'},
    {
        'question': 'Zdarza sie często, że ludzie zwracają mi uwagę ,że to co właśnie powiedziałem jest niegrzeczne, choć ja mam wrażenie , że to było grzeczne',
        'answers': ['Zgadzam sie', 'Nie zgadzam się'],
        'good_answer': 'Zgadzam sie'},
    {'question': 'Gdy czytam jakąś książkę, potrafię sobie łatwo wyobrazić, jak wyglądają bohaterowie',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Nie zgadzam się'},
    {'question': 'Jestem zafascynowany datami',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Zgadzam sie'},
    {'question': 'Nie mam kłopotów z rozumieniem wypowiedzi, nawet gdy równocześnie dyskutuje kilka osób',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Nie zgadzam się'},
    {'question': 'Spotkania towarzyskie nie stanowią dla mnie problemu',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Nie zgadzam się'},
    {'question': 'Zauważam szczegóły, które nie są widoczne dla innych',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Zgadzam sie'},
    {'question': 'Wole pójść do biblioteki niż na imprezę/ przyjęcie',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Zgadzam sie'},
    {'question': 'Nie mam problemów z wymyślaniem historyjek',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Nie zgadzam się'},
    {'question': 'Bardziej przywiązuję się do osób niż do przedmiotów',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Nie zgadzam się'},
    {
        'question': 'Kiedy zajmuję się jakimś problemem, denerwuję się, gdy musze przerwać to co robię i nie mogę kontynuować swoich działań',
        'answers': ['Zgadzam sie', 'Nie zgadzam się'],
        'good_answer': 'Zgadzam sie'},
    {'question': 'Lubię pogaduszki o niczym, np. w windzie',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Nie zgadzam się'},
    {'question': 'Jeżeli coś mówię, to często nie dopuszczam innych do głosu',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Zgadzam sie'},
    {'question': 'Jestem zafascynowany numerami',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Zgadzam sie'},
    {'question': 'Kiedy czytam książkę, mam kłopot z wyobrażeniem sobie postaci',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Zgadzam sie'},
    {'question': 'Czytanie beletrystyki nie sprawia mi przyjemności',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Zgadzam sie'},
    {'question': 'Mam kłopot z nawiązywaniem przyjaźni',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Zgadzam sie'},
    {'question': 'Bardzo często zauważam, że rzeczy układają się według wzorów, szablonów',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Zgadzam sie'},
    {'question': 'Wole pójść do teatru niż do muzeum',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Nie zgadzam się'},
    {'question': 'Nie przeszkadza mi to wcale, gdy mój rytm dnia jest w jakiś sposób zakłócony',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Nie zgadzam się'},
    {'question': 'Często łapię się na tym, że nie wiem, jak podtrzymać rozmowę',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Zgadzam sie'},
    {'question': 'Nie mam problemów z tym, by "czytać miedzy wierszami", gdy ktoś coś do mnie mówi',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Nie zgadzam się'},
    {'question': 'Bardziej koncentruje się na całości, niż na szczegółach',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Nie zgadzam się'},
    {'question': 'Mam problem z zapamiętywaniem numerów telefonów',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Nie zgadzam się'},
    {'question': 'Zazwyczaj nie zauważam drobnych zmian w położeniu lub wyglądzie osób',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Nie zgadzam się'},
    {'question': 'Zauważam, kiedy to co mówię zaczyna innych nudzić',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Nie zgadzam się'},
    {'question': 'Nie mam problemu z tym, by równocześnie wykonywać więcej niż jedno zadanie',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Nie zgadzam się'},
    {'question': 'Kiedy rozmawiam przez telefon, nie jestem pewien, czyja jest kolej (na powiedzenie czegoś)',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Zgadzam sie'},
    {'question': 'lubię robić wiele rzeczy równocześnie',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Nie zgadzam się'},
    {'question': 'Często jestem ostatnią osoba, która rozumie puentę żartu',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Zgadzam sie'},
    {'question': 'Nie sprawia mi problemu odgadnięcie co jakaś osoba myśli lub czuje na podstawie jej wyrazu twarzy',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Nie zgadzam się'},
    {
        'question': 'Jeżeli z jakiegoś powodu musze przerwać to co robię, nie mam problemu z natychmiastowym powrotem do tego zajęcia',
        'answers': ['Zgadzam sie', 'Nie zgadzam się'],
        'good_answer': 'Nie zgadzam się'},
    {'question': 'Potrafię rozmawiać o niczym',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Nie zgadzam się'},
    {'question': 'Ludzie zwracają mi uwagę, że rozmawiam ciągle na ten sam temat',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Zgadzam sie'},
    {'question': 'Kiedy byłem dzieckiem lubiłem bawić się w przebieranie i udawanie, że jestem kimś innym',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Nie zgadzam się'},
    {'question': 'Lubię zbierać informacje na temat różnych kategorii przedmiotów ( gatunki ptaków, marki samochodów)',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Zgadzam sie'},
    {'question': 'Mam kłopoty z wyobrażeniem sobie, jak by to było, gdybym był kimś innym',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Zgadzam sie'},
    {'question': 'Lubię, gdy każda aktywność, w której mam brać udział jest starannie zaplanowana',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Zgadzam sie'},
    {'question': 'Lubię spotkania towarzyskie',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Nie zgadzam się'},
    {'question': 'Rozpoznawanie ludzkich emocji jest dla mnie trudne',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Zgadzam sie'},
    {'question': 'Jestem niespokojny/ nerwowy w nowych sytuacjach',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Zgadzam sie'},
    {'question': 'Lubię poznawać nowych ludzi',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Nie zgadzam się'},
    {'question': 'Jestem dobrym dyplomatą',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Nie zgadzam się'},
    {'question': 'Zapamiętywanie dat urodzin jest dla mnie problemem',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Nie zgadzam się'},
    {'question': 'Bawienie się z dziećmi, gdy musze coś lub kogoś udawać, jest dla mnie łatwe',
     'answers': ['Zgadzam sie', 'Nie zgadzam się'],
     'good_answer': 'Nie zgadzam się'},
]
